/**
 * Dataset base de DECODE.
 * Las portadas son gradientes generados (no hay assets binarios en el repo):
 * cada álbum trae `cover` con dos colores y un patrón que AlbumCard sabe pintar.
 */
export const ALBUMS = [
  {
    id: 'cemento',
    title: 'Cemento',
    artist: 'Los Brutos del Riachuelo',
    year: 2025,
    genres: ['Post-punk', 'Rock Argentino'],
    score: 8.7,
    label: 'Trapecio Discos',
    duration: '41 min',
    tracks: 11,
    featured: true,
    cover: { from: '#4B2E83', to: '#D6408A', pattern: 'stripes' },
    excerpt:
      'Un disco que suena a sótano húmedo y a ciudad que no perdona: once canciones que convierten el ruido de obra en liturgia.',
    pullQuote:
      'No hay nostalgia acá. Hay una banda mirando el pozo y decidiendo cantarle en la cara.',
    body: [
      'Hay discos que se escriben desde la distancia y discos que se escriben con los pies en el barro. *Cemento* es de los segundos. Los Brutos del Riachuelo llevaban cuatro años tocando en galpones del sur del conurbano, y ese kilometraje se escucha: la batería de Faustino Rivas suena grabada en una habitación real, con paredes que devuelven el golpe medio segundo tarde.',
      'El disco abre con "Mampostería", casi seis minutos de un bajo que no se mueve de la nota mientras las guitarras se van desafinando por decisión propia. Es una declaración de método más que de principios: acá nada se va a resolver, todo se va a sostener hasta que se rompa.',
      'La segunda mitad es donde el grupo se juega. "Vereda Rota" y "Tres de la Mañana" abandonan la abrasión por algo más incómodo — melodías que casi funcionan, estribillos que se retiran justo antes de entregarse. Es un gesto arriesgado y no siempre sale: "Pileta Vacía" se queda a mitad de camino entre el bosquejo y la canción.',
      'Pero el cierre, "Cemento", redime cualquier titubeo. Ocho minutos que empiezan en un susurro y terminan en un muro de feedback sobre el que Ximena Ferrari repite una sola línea hasta gastarla. Cuando el ruido cae de golpe, lo que queda no es alivio: es la sensación de haber estado escuchando algo que no debía terminar tan pronto.',
    ],
    reviewer: 'Paloma Iriarte',
    date: '2025-11-08',
  },
  {
    id: 'humedad-tropical',
    title: 'Humedad Tropical',
    artist: 'Ceci Maravilla',
    year: 2025,
    genres: ['Neoperreo', 'Pop Experimental'],
    score: 9.1,
    label: 'Autogestionado',
    duration: '33 min',
    tracks: 10,
    cover: { from: '#D6408A', to: '#B5C934', pattern: 'dots' },
    excerpt:
      'Diez cortes de perreo mutante donde el reguetón se derrite y vuelve a armarse mal, a propósito, y mejor.',
    pullQuote: 'Maravilla no cita el club: lo desarma y lo vuelve a pegar torcido.',
    body: [
      'El segundo disco de Ceci Maravilla llega dos años después de *Fiebre*, y la distancia le sentó bien. Donde aquel era un ejercicio de acumulación, *Humedad Tropical* es de sustracción: menos capas, más espacio, y una producción que deja respirar los silencios entre los golpes.',
      'La paleta es reconocible — dembow, sintes baratos, la voz procesada hasta el filo — pero el uso es otro. En "Vaho", el beat entra recién al minuto y medio, después de que la voz haya sostenido sola una melodía que no se parece a nada del género.',
      'Lo notable es la escritura. Maravilla canta sobre el cansancio de la fiesta sin moralizar, con una precisión de detalle que la separa de sus pares: el aire acondicionado que gotea, el taxi que no llega, la mano que se suelta.',
      'Si algo se le puede reprochar es la brevedad. Treinta y tres minutos que pasan como quince, y un final — "Amanecer en la Ruta 2" — que insinúa un disco entero que todavía no existe.',
    ],
    reviewer: 'Tomás Beltrán',
    date: '2025-11-02',
  },
  {
    id: 'archivo-muerto',
    title: 'Archivo Muerto',
    artist: 'Delta Vacío',
    year: 2024,
    genres: ['Ambient', 'Drone'],
    score: 7.4,
    label: 'Nublado Tapes',
    duration: '68 min',
    tracks: 6,
    cover: { from: '#77705f', to: '#C9BFA6', pattern: 'grid' },
    excerpt:
      'Seis piezas construidas con grabaciones de campo de estaciones de tren clausuradas. Bello, ocasionalmente inerte.',
    pullQuote: 'El disco funciona mejor como espacio que como narración.',
    body: [
      'Delta Vacío es el proyecto solista de Irene Kovacs, y *Archivo Muerto* es su trabajo más ambicioso: sesenta y ocho minutos armados casi enteramente con grabaciones tomadas en once estaciones ferroviarias abandonadas del interior bonaerense.',
      'Las mejores piezas son las que resisten la tentación de embellecer. "Andén 3" deja el material casi crudo — viento, chapa, un perro lejos — y suma apenas un pedal de órgano que aparece a los cuatro minutos y ya no se va.',
      'Cuando Kovacs interviene más, el disco pierde. "Boletería" apila reverbs hasta que el origen del sonido se vuelve irrelevante, y lo que quedaba de documento se convierte en textura genérica.',
      'Aun así hay una honestidad en el proyecto que lo sostiene. No pretende conmover con la ruina; la registra y se corre. Es menos de lo que podría haber sido y bastante más de lo que suele ofrecerse bajo esta etiqueta.',
    ],
    reviewer: 'Paloma Iriarte',
    date: '2025-10-21',
  },
  {
    id: 'nafta-super',
    title: 'Nafta Súper',
    artist: 'Las Hermanas Quiroga',
    year: 2025,
    genres: ['Cumbia', 'Psicodelia'],
    score: 8.2,
    label: 'Trapecio Discos',
    duration: '38 min',
    tracks: 9,
    cover: { from: '#B5C934', to: '#4B2E83', pattern: 'waves' },
    excerpt:
      'Cumbia santafesina pasada por un fuzz de los setenta. Suena a viaje largo con la ventanilla baja.',
    pullQuote: 'Es un disco de manejar, y sabe exactamente qué ruta está recorriendo.',
    body: [
      'Las Hermanas Quiroga no son hermanas ni se apellidan Quiroga, pero tocan como si hubieran compartido casa toda la vida. *Nafta Súper* es su tercer disco y el primero donde el chiste del nombre deja de importar.',
      'El armado es simple: acordeón, güira, bajo, y una guitarra con más distorsión de la que la cumbia suele tolerar. La tensión entre esos dos mundos es todo el disco, y en "Ruta 11" alcanza un punto donde ya no se sabe qué género se está escuchando.',
      'Hay momentos de relleno — dos instrumentales en el medio que podrían haber sido uno — pero el nivel de las canciones con voz es alto y parejo. "Estación de Servicio" tiene el mejor estribillo que va a escucharse este año en cualquier género.',
      'Un disco sin pretensiones que termina siendo más ambicioso que muchos que sí las tienen.',
    ],
    reviewer: 'Nadia Sforza',
    date: '2025-10-14',
  },
  {
    id: 'silabario',
    title: 'Silabario',
    artist: 'Rubén Cortés',
    year: 2024,
    genres: ['Folclore', 'Canción'],
    score: 6.1,
    label: 'Pampa Sur',
    duration: '45 min',
    tracks: 12,
    cover: { from: '#C9BFA6', to: '#D6408A', pattern: 'stripes' },
    excerpt:
      'Un cantautor con oficio que esta vez confunde la contención con la falta de riesgo.',
    pullQuote: 'Todo está bien hecho. Ese es exactamente el problema.',
    body: [
      'Rubén Cortés tiene treinta años de carrera y una obra que merece más atención de la que recibe. *Silabario*, su noveno disco, no va a cambiar eso, y la responsabilidad es suya.',
      'La grabación es impecable, los arreglos de cuerdas de Mora Bianchi son elegantes, y las doce canciones cumplen. Pero cumplir es un piso, no un techo, y el disco se instala ahí sin moverse.',
      'Las letras, siempre su punto fuerte, suenan esta vez a fórmula: la imagen del río, el padre ausente, el pueblo que se vacía. Cortés escribió estas mismas canciones mejor en *Camino de Tierra* (2011).',
      'Hay dos excepciones que duelen por lo que insinúan. "Carta a Nadie" y "El Último Tren" tienen la aspereza que le falta al resto — voz al frente, guitarra sola, ninguna red. Doce de esas y estaríamos hablando de otra cosa.',
    ],
    reviewer: 'Tomás Beltrán',
    date: '2025-09-30',
  },
  {
    id: 'ruido-blanco',
    title: 'Ruido Blanco / Ruido Negro',
    artist: 'Mecánica Popular',
    year: 2023,
    genres: ['Noise', 'Electrónica'],
    score: 5.8,
    label: 'Nublado Tapes',
    duration: '52 min',
    tracks: 8,
    cover: { from: '#1A1A1A', to: '#77705f', pattern: 'grid' },
    excerpt: 'Un disco doble conceptual que confunde la duración con la profundidad.',
    pullQuote: 'La idea era buena. Duraba diez minutos.',
    body: [
      'La premisa de *Ruido Blanco / Ruido Negro* es atractiva sobre el papel: dos suites de veintiséis minutos, una construida enteramente por adición y la otra por sustracción, partiendo del mismo material fuente.',
      'La primera mitad casi funciona. La acumulación tiene lógica y hay un tramo, entre los minutos ocho y catorce, donde el peso del sonido genera algo parecido a una emoción.',
      'La segunda mitad es donde el concepto se come al disco. Sustraer capas de un material que nunca fue del todo interesante deja, previsiblemente, cada vez menos. Los últimos ocho minutos son casi silencio, y no del tipo cargado.',
      'Mecánica Popular es un dúo capaz — sus EPs de 2021 lo prueban — pero acá se enamoraron de un diagrama y se olvidaron de escuchar el resultado.',
    ],
    reviewer: 'Nadia Sforza',
    date: '2025-09-12',
  },
  {
    id: 'verano-del-98',
    title: 'Verano del 98',
    artist: 'Puente Alsina',
    year: 2025,
    genres: ['Indie Rock', 'Shoegaze'],
    score: 7.9,
    label: 'Autogestionado',
    duration: '36 min',
    tracks: 10,
    cover: { from: '#4B2E83', to: '#C9BFA6', pattern: 'dots' },
    excerpt:
      'Guitarras en capas y melodías enterradas: un debut que sabe esconder sus mejores momentos.',
    pullQuote: 'Un disco que premia al que sube el volumen y espera.',
    body: [
      'El debut de Puente Alsina llega con todas las referencias a la vista — el shoegaze de los noventa, el indie porteño de la última década — y aun así logra sonar a algo propio en al menos cuatro canciones.',
      'El truco está en la mezcla. Federico Anguita puso la voz tres decibeles más abajo de lo que cualquier productor razonable recomendaría, y esa decisión define el disco: las letras se adivinan más que se entienden, y funciona.',
      'Las canciones más rápidas son las más débiles. "Pileta" y "Ruido de Autos" corren detrás de una energía que la banda todavía no tiene en vivo.',
      'Pero "Enero", siete minutos de acumulación paciente, es la mejor canción de un grupo debutante que se escuchó este año en el circuito. El resto del disco existe para justificarla, y alcanza.',
    ],
    reviewer: 'Paloma Iriarte',
    date: '2025-08-26',
  },
  {
    id: 'monte-adentro',
    title: 'Monte Adentro',
    artist: 'Ayelén Ocampo',
    year: 2023,
    genres: ['Folclore', 'Ambient'],
    score: 8.9,
    label: 'Pampa Sur',
    duration: '49 min',
    tracks: 8,
    cover: { from: '#B5C934', to: '#77705f', pattern: 'waves' },
    excerpt:
      'Chacarera desmontada y reconstruida con sintetizadores modulares. Suena inevitable.',
    pullQuote: 'La tradición no aparece acá como cita sino como estructura ósea.',
    body: [
      'Ayelén Ocampo estudió composición en Córdoba y creció escuchando a su abuelo tocar chacareras en un patio de Santiago. *Monte Adentro* es el primer disco donde esas dos formaciones dejan de negociar y se funden.',
      'La instrumentación es desconcertante en el mejor sentido: bombo legüero procesado hasta volverse un pulso electrónico, violín que entra y sale de la afinación temperada, y un sistema modular que Ocampo toca como si fuera un instrumento acústico más.',
      'Lo que impide que el proyecto se vuelva un ejercicio es la escritura. "Camino Viejo" y "La Que Se Fue" son canciones antes que conceptos, con estructuras que un guitarrista de peña reconocería aunque el timbre le resultara marciano.',
      'A dos años de su salida, el disco creció. Se escucha ahora como el punto de partida de algo que todavía no tiene nombre.',
    ],
    reviewer: 'Nadia Sforza',
    date: '2025-08-11',
  },
  {
    id: 'kiosco-24h',
    title: 'Kiosco 24H',
    artist: 'DJ Sopa',
    year: 2024,
    genres: ['Electrónica', 'Neoperreo'],
    score: 6.8,
    label: 'Autogestionado',
    duration: '29 min',
    tracks: 12,
    cover: { from: '#D6408A', to: '#4B2E83', pattern: 'grid' },
    excerpt:
      'Doce miniaturas de club, algunas brillantes, varias descartables. Un mixtape que se hace pasar por disco.',
    pullQuote: 'Cuando acierta, no hay nada más divertido saliendo del under.',
    body: [
      'DJ Sopa viene de la escena de fiestas de La Plata y *Kiosco 24H* tiene exactamente esa energía: veintinueve minutos, doce pistas, ninguna que llegue a los tres minutos.',
      'El formato es la fortaleza y el límite. Las ideas se presentan y se abandonan antes de gastarse — "Alfajor" dura noventa segundos y no necesita más — pero también significa que nada llega a construirse.',
      'Los picos son reales. "Fernet en Vaso de Plástico" y "3AM Panadería" tienen una gracia rítmica que no se enseña.',
      'Los valles también. Tres o cuatro pistas suenan a bocetos guardados por costumbre, y en un disco tan corto ese lastre pesa el doble.',
    ],
    reviewer: 'Tomás Beltrán',
    date: '2025-07-19',
  },
];
